### ISSUE TITLE
llm_perf 厂商接入时torch的版本问题

### ISSUE THREAD

**Issue by yizhou-xu** [bytedance/ByteMLPerf#116]
请问llm_perf厂商接入时必须使用2.0.1版本的torch吗？ 参考文档：https://bytemlperf.ai/zh/guide/inference_llm_vendor.html

**Comment by suisiyuan** [comment]
没有torch版本需求，根据厂商自己适配的torch版本来，目前torch2.3会用的比较多一点。

**Comment by yizhou-xu** [comment]
了解了，谢谢。上面的文档也许可以修改下，里面写的是要求2.0.1版本。

**Comment by yizhou-xu** [comment]
https://bytemlperf.ai/zh/guide/inference_llm_vendor.html  请问下为什么这个页面无法正常显示内容了？

**Comment by suisiyuan** [comment]
> https://bytemlperf.ai/zh/guide/inference_llm_vendor.html 请问下为什么这个页面无法正常显示内容了？

已经修复了。

**Comment by Yi-sir** [comment]
好的谢谢❤
