### ISSUE TITLE
general_perf厂商接入的环境问题

### ISSUE THREAD

**Issue by Yi-sir** [bytedance/ByteMLPerf#118]
可以绕过venv，直接使用docker部署交付吗？因为模型编译工具链对环境有一定要求。

**Comment by suisiyuan** [comment]
可以，那就不用venv，直接在docker里面装好环境直接跑就行。

**Comment by Yi-sir** [comment]
好的谢谢❤

**Comment by Yi-sir** [comment]
请问下general_perf里面，runtime_backend的load接口是什么含义？看到注释与version接口相同
