### ISSUE TITLE
can not run gp2  on habana gaudi2

### ISSUE THREAD

**Issue by ZhaiFeiyue** [bytedance/ByteMLPerf#34]
when we try to run gpt2 torch script on habana gaudi2, there is a error comes, see following picture
![image](https://github.com/bytedance/ByteMLPerf/assets/80079571/2f7c29b7-cebb-4d36-99cc-c7adef142a66)

it is due to the device type of input tensors are not same, one is hpu and another is cpu
![image](https://github.com/bytedance/ByteMLPerf/assets/80079571/48d8a71a-cd4c-4bfe-91c8-6ae87200148c)

**Comment by JianzheXiao** [comment]
Hi! Could you please remove the original gpt2 model and rerun the command to see if this error got fixed?

**Comment by Minghui-BD** [comment]
fixed
