### ISSUE TITLE
请教下目前 model_zoo 中提供的 fp32 的模型，有提供工具或者方法快速转换为 fp

### ISSUE THREAD

**Issue by eric-yq** [bytedance/ByteMLPerf#38]

**Comment by eric-yq** [comment]
请教下目前 model_zoo 中提供的 fp32 的模型，有提供工具或者方法快速转换为 fp16 模型吗？
打算用 ARM CPU 进行推理 Benchmark，想看看 FP16 性能如何。
如果工具集有提供了快速进行转换精度的工具或者方法，麻烦各位指导一下。多谢了。

**Comment by JianzheXiao** [comment]
> 请教下目前 model_zoo 中提供的 fp32 的模型，有提供工具或者方法快速转换为 fp16 模型吗？ 打算用 ARM CPU 进行推理 Benchmark，想看看 FP16 性能如何。 如果工具集有提供了快速进行转换精度的工具或者方法，麻烦各位指导一下。多谢了。

 框架本身是没有提供低精度量化功能的，这一块其实是交给各个厂商的Backend去做，如果想要去做ARM CPU FP16的测试的话可以在对应的CPU Backend里面手动添加一下最简单的也可以直接model.half()
