### ISSUE TITLE
SD-Vae-decoder 输入是否有误？

### ISSUE THREAD

**Issue by Ivorfeng** [bytedance/ByteMLPerf#44]
Vae-decoder输入256对应2048输出，这个规模有点太大了，
unet 输入hw 32, 输出hw 32, 以及vae-encoder 输入hw 256，输出hw 32，
推测vae-decoder 输入应该是32?

**Comment by JianzheXiao** [comment]
https://github.com/bytedance/ByteMLPerf/commit/031a1ba21439548db52ec088eee6c6a6ad2cec67 Fixed
