### ISSUE TITLE
python 3.10.12无法启动

### ISSUE THREAD

**Issue by incomingflyingbrick** [bytedance/ByteMLPerf#72]
你好，我在做llm测试
这个是我使用的命令，但是运行之后报错了，请问可以看一下么？

python3 launch.py --task chatglm2-torch-fp16-6b --hardware_type GPU

运行报错
ImportError: cannot import name 'TypeGuard' from 'typing_extensions' (/usr/local/lib/python3.10/dist-packages/typing_extensions.py)

**Comment by suisiyuan** [comment]
更新一下typing_extensions的版本。

**Comment by incomingflyingbrick** [comment]
可以了，现在close issue
